import '../lawn_business_five_tab_container_screen/widgets/lawnbusinessfivetabcontainer_item_widget.dart';import 'bloc/lawn_business_five_tab_container_bloc.dart';import 'models/lawn_business_five_tab_container_model.dart';import 'models/lawnbusinessfivetabcontainer_item_model.dart';import 'package:flutter/material.dart';import 'package:sanjay_s_application2/core/app_export.dart';import 'package:sanjay_s_application2/presentation/lawn_business_five_page/lawn_business_five_page.dart';import 'package:sanjay_s_application2/widgets/custom_outlined_button.dart';import 'package:sanjay_s_application2/widgets/custom_text_form_field.dart';class LawnBusinessFiveTabContainerScreen extends StatefulWidget {const LawnBusinessFiveTabContainerScreen({Key? key}) : super(key: key);

@override LawnBusinessFiveTabContainerScreenState createState() =>  LawnBusinessFiveTabContainerScreenState();

static Widget builder(BuildContext context) { return BlocProvider<LawnBusinessFiveTabContainerBloc>(create: (context) => LawnBusinessFiveTabContainerBloc(LawnBusinessFiveTabContainerState(lawnBusinessFiveTabContainerModelObj: LawnBusinessFiveTabContainerModel()))..add(LawnBusinessFiveTabContainerInitialEvent()), child: LawnBusinessFiveTabContainerScreen()); } 
 }

// ignore_for_file: must_be_immutable
class LawnBusinessFiveTabContainerScreenState extends State<LawnBusinessFiveTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 5, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 11.v), Expanded(child: SingleChildScrollView(child: SizedBox(height: 2970.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeftWhiteA700, height: 24.v, width: 22.h, alignment: Alignment.topLeft, margin: EdgeInsets.only(left: 24.h, top: 7.v), onTap: () {onTapImgArrowLeft(context);}), _buildArrowLeft(context), Align(alignment: Alignment.bottomCenter, child: SizedBox(height: 2718.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(height: 2718.v, width: double.maxFinite, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.vertical(top: Radius.circular(15.h))))), _buildViewAllAlbums(context), _buildEnterName(context)])))]))))])))); } 
/// Section Widget
Widget _buildArrowLeft(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 19.v), decoration: AppDecoration.fillBlueGray, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgVector, height: 2.v, width: 15.h, margin: EdgeInsets.only(left: 17.h)), SizedBox(height: 75.v), CustomImageView(imagePath: ImageConstant.imgImage14, height: 44.adaptSize, width: 44.adaptSize, alignment: Alignment.center), SizedBox(height: 82.v), Align(alignment: Alignment.centerRight, child: Container(padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 3.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder9), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgPicture1, height: 9.adaptSize, width: 9.adaptSize, margin: EdgeInsets.symmetric(vertical: 1.v)), Padding(padding: EdgeInsets.only(left: 6.h, top: 1.v, right: 1.h), child: Text("lbl_0_photos".tr, style: theme.textTheme.labelSmall))]))), SizedBox(height: 21.v)]))); } 
/// Section Widget
Widget _buildViewAllAlbumsButton(BuildContext context) { return CustomOutlinedButton(width: 107.h, text: "msg_view_all_albums".tr, margin: EdgeInsets.only(left: 116.h), buttonStyle: CustomButtonStyles.outlinePrimary); } 
/// Section Widget
Widget _buildEnterhere(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 14.h), child: BlocSelector<LawnBusinessFiveTabContainerBloc, LawnBusinessFiveTabContainerState, TextEditingController?>(selector: (state) => state.enterhereController, builder: (context, enterhereController) {return CustomTextFormField(controller: enterhereController, hintText: "msg_enter_here".tr, hintStyle: CustomTextStyles.bodySmallGray40002, contentPadding: EdgeInsets.symmetric(horizontal: 4.h));})); } 
/// Section Widget
Widget _buildEnterhere1(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 14.h), child: BlocSelector<LawnBusinessFiveTabContainerBloc, LawnBusinessFiveTabContainerState, TextEditingController?>(selector: (state) => state.enterhereController1, builder: (context, enterhereController1) {return CustomTextFormField(controller: enterhereController1, hintText: "msg_enter_here".tr, hintStyle: CustomTextStyles.bodySmallGray40002, contentPadding: EdgeInsets.symmetric(horizontal: 4.h));})); } 
/// Section Widget
Widget _buildEnterhere2(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 14.h), child: BlocSelector<LawnBusinessFiveTabContainerBloc, LawnBusinessFiveTabContainerState, TextEditingController?>(selector: (state) => state.enterhereController2, builder: (context, enterhereController2) {return CustomTextFormField(controller: enterhereController2, hintText: "msg_enter_here".tr, hintStyle: CustomTextStyles.bodySmallGray40002, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 4.h));})); } 
/// Section Widget
Widget _buildReadMoreButton(BuildContext context) { return CustomOutlinedButton(height: 25.v, width: 87.h, text: "lbl_read_more".tr, margin: EdgeInsets.only(left: 126.h), buttonStyle: CustomButtonStyles.outlinePrimary); } 
/// Section Widget
Widget _buildViewAllAlbums(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(left: 18.h, top: 615.v, right: 3.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 19.h), child: Text("lbl_videos_0".tr, style: CustomTextStyles.labelLargeBlack90001_2)), SizedBox(height: 27.v), Padding(padding: EdgeInsets.only(right: 6.h), child: BlocSelector<LawnBusinessFiveTabContainerBloc, LawnBusinessFiveTabContainerState, LawnBusinessFiveTabContainerModel?>(selector: (state) => state.lawnBusinessFiveTabContainerModelObj, builder: (context, lawnBusinessFiveTabContainerModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 172.v, crossAxisCount: 2, mainAxisSpacing: 11.h, crossAxisSpacing: 11.h), physics: NeverScrollableScrollPhysics(), itemCount: lawnBusinessFiveTabContainerModelObj?.lawnbusinessfivetabcontainerItemList.length ?? 0, itemBuilder: (context, index) {LawnbusinessfivetabcontainerItemModel model = lawnBusinessFiveTabContainerModelObj?.lawnbusinessfivetabcontainerItemList[index] ?? LawnbusinessfivetabcontainerItemModel(); return LawnbusinessfivetabcontainerItemWidget(model);});})), SizedBox(height: 14.v), _buildViewAllAlbumsButton(context), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 14.h), child: Text("msg_about_lawn_events".tr, style: CustomTextStyles.titleSmallBlack90001SemiBold)), SizedBox(height: 12.v), _buildEnterhere(context), SizedBox(height: 19.v), Padding(padding: EdgeInsets.only(left: 14.h), child: Text("lbl_since".tr, style: CustomTextStyles.labelSmallSemiBold_1)), SizedBox(height: 11.v), _buildEnterhere1(context), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 14.h), child: Text("msg_candid_photography".tr, style: CustomTextStyles.labelSmallSemiBold_1)), SizedBox(height: 20.v), _buildEnterhere2(context), SizedBox(height: 20.v), _buildReadMoreButton(context)]))); } 
/// Section Widget
Widget _buildAlbumsZero(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 21.h), child: Text("lbl_albums_0".tr, style: CustomTextStyles.labelLargeBlack90001_2)), SizedBox(height: 9.v), Container(height: 21.v, width: 357.h, margin: EdgeInsets.only(left: 18.h), child: TabBar(controller: tabviewController, isScrollable: true, labelColor: appTheme.whiteA700, labelStyle: TextStyle(fontSize: 10.fSize, fontFamily: 'Kumbh Sans', fontWeight: FontWeight.w500), unselectedLabelColor: appTheme.gray50005, unselectedLabelStyle: TextStyle(fontSize: 10.fSize, fontFamily: 'Kumbh Sans', fontWeight: FontWeight.w500), indicator: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(10.h)), tabs: [Tab(child: Text("lbl_all_cities_0".tr)), Tab(child: Text("lbl_hydrabad_0".tr)), Tab(child: Text("lbl_mumbai_0".tr)), Tab(child: Text("lbl_bengaluru_0".tr)), Tab(child: Text("lbl_chennai_32".tr))]))]); } 
/// Section Widget
Widget _buildEnterName(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 27.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 32.h), child: Text("lbl_enter_name".tr, style: CustomTextStyles.titleLargeBluegray10003)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 32.h), child: Text("lbl_city".tr, style: CustomTextStyles.labelLargeBluegray10003)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 32.h), child: Text("lbl_photo_video".tr, style: CustomTextStyles.labelSmallGray50005)), Padding(padding: EdgeInsets.only(left: 32.h), child: Row(children: [Text("lbl_price".tr, style: CustomTextStyles.titleLargePrimary), Padding(padding: EdgeInsets.only(left: 32.h, top: 9.v, bottom: 4.v), child: Text("lbl_per_day".tr, style: theme.textTheme.labelSmall))])), Padding(padding: EdgeInsets.only(left: 32.h), child: Text("lbl_pricing_info".tr, style: CustomTextStyles.labelSmallGray50005.copyWith(decoration: TextDecoration.underline))), SizedBox(height: 15.v), _buildAlbumsZero(context), SizedBox(height: 1162.v, child: TabBarView(controller: tabviewController, children: [LawnBusinessFivePage(), LawnBusinessFivePage(), LawnBusinessFivePage(), LawnBusinessFivePage(), LawnBusinessFivePage()]))]))); } 

/// Navigates to the previous screen.
onTapImgArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
