import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import '../models/rewindlist_item_model.dart';import '../models/widget_item_model.dart';import '../models/banquettext_item_model.dart';import '../models/userprofilelist1_item_model.dart';import '../models/rectangle_item_model.dart';import 'package:sanjay_s_application2/presentation/homepage_screen/models/homepage_model.dart';part 'homepage_event.dart';part 'homepage_state.dart';/// A bloc that manages the state of a Homepage according to the event that is dispatched to it.
class HomepageBloc extends Bloc<HomepageEvent, HomepageState> {HomepageBloc(HomepageState initialState) : super(initialState) { on<HomepageInitialEvent>(_onInitialize); }

List<RewindlistItemModel> fillRewindlistItemList() { return [RewindlistItemModel(rewind: ImageConstant.imgRewind)]; } 
List<WidgetItemModel> fillWidgetItemList() { return List.generate(1, (index) => WidgetItemModel()); } 
List<BanquettextItemModel> fillBanquettextItemList() { return [BanquettextItemModel(banquetImage: ImageConstant.imgEllipse150, banquetText: "Banquet"), BanquettextItemModel(banquetImage: ImageConstant.imgEllipse151, banquetText: "Lawns"), BanquettextItemModel(banquetImage: ImageConstant.imgEllipse152, banquetText: "Food"), BanquettextItemModel(banquetImage: ImageConstant.imgEllipse153, banquetText: "Decoration"), BanquettextItemModel(banquetImage: ImageConstant.imgEllipse150, banquetText: "Banquet"), BanquettextItemModel(banquetImage: ImageConstant.imgEllipse150, banquetText: "Banquet"), BanquettextItemModel(banquetImage: ImageConstant.imgEllipse151, banquetText: "Lawns"), BanquettextItemModel(banquetImage: ImageConstant.imgEllipse152, banquetText: "Food"), BanquettextItemModel(banquetImage: ImageConstant.imgEllipse153, banquetText: "Decoration"), BanquettextItemModel(banquetText: "Show More")]; } 
List<Userprofilelist1ItemModel> fillUserprofilelist1ItemList() { return [Userprofilelist1ItemModel(userImage: ImageConstant.imgRectangle4259157x149, bookmark: ImageConstant.imgBookmark, ratingText: "4.5", photographerText: "Photographer")]; } 
List<RectangleItemModel> fillRectangleItemList() { return [RectangleItemModel(rectangle: ImageConstant.imgRectangle4263157x149), RectangleItemModel(rectangle: ImageConstant.imgRectangle4261157x149), RectangleItemModel(rectangle: ImageConstant.imgStarSymbolIconYellowA700), RectangleItemModel(rectangle: ImageConstant.imgStarSymbolIconYellowA700), RectangleItemModel(rectangle: ImageConstant.imgStarSymbolIconYellowA700)]; } 
_onInitialize(HomepageInitialEvent event, Emitter<HomepageState> emit, ) async  { emit(state.copyWith(sliderIndex: 0)); emit(state.copyWith(homepageModelObj: state.homepageModelObj?.copyWith(rewindlistItemList: fillRewindlistItemList(), widgetItemList: fillWidgetItemList(), banquettextItemList: fillBanquettextItemList(), userprofilelist1ItemList: fillUserprofilelist1ItemList(), rectangleItemList: fillRectangleItemList()))); } 
 }
