import 'bloc/sign_up_bloc.dart';import 'models/sign_up_model.dart';import 'package:flutter/material.dart';import 'package:sanjay_s_application2/core/app_export.dart';import 'package:sanjay_s_application2/core/utils/validation_functions.dart';import 'package:sanjay_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:sanjay_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:sanjay_s_application2/widgets/custom_elevated_button.dart';import 'package:sanjay_s_application2/widgets/custom_icon_button.dart';import 'package:sanjay_s_application2/widgets/custom_text_form_field.dart';import 'package:sanjay_s_application2/domain/googleauth/google_auth_helper.dart';import 'package:sanjay_s_application2/domain/facebookauth/facebook_auth_helper.dart';
// ignore_for_file: must_be_immutable
class SignUpScreen extends StatelessWidget {SignUpScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<SignUpBloc>(create: (context) => SignUpBloc(SignUpState(signUpModelObj: SignUpModel()))..add(SignUpInitialEvent()), child: SignUpScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(color: appTheme.whiteA700, image: DecorationImage(image: AssetImage(ImageConstant.imgSignUp), fit: BoxFit.cover)), child: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 14.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 30.v, width: 85.h, margin: EdgeInsets.only(left: 5.h), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 3.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgG430, height: 1.adaptSize, width: 1.adaptSize), CustomImageView(imagePath: ImageConstant.imgPath534, height: 1.adaptSize, width: 1.adaptSize)]))), Align(alignment: Alignment.center, child: Text("lbl_sign_up".tr, style: CustomTextStyles.headlineSmallMedium))])), SizedBox(height: 73.v), _buildFullName(context), SizedBox(height: 43.v), _buildMobileNumber(context), SizedBox(height: 43.v), Align(alignment: Alignment.center, child: SizedBox(height: 58.v, width: 271.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapArrowLeft(context);}, child: Container(height: 58.v, width: 271.h, padding: EdgeInsets.all(14.h), decoration: AppDecoration.outlineIndigoF.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: CustomIconButton(height: 30.adaptSize, width: 30.adaptSize, padding: EdgeInsets.all(8.h), decoration: IconButtonStyleHelper.fillIndigoA, alignment: Alignment.centerRight, child: CustomImageView(imagePath: ImageConstant.imgArrowLeft))))), Align(alignment: Alignment.center, child: Text("lbl_sign_up".tr.toUpperCase(), style: CustomTextStyles.titleMediumWhiteA700))]))), SizedBox(height: 50.v), Padding(padding: EdgeInsets.only(left: 145.h), child: Text("lbl_or".tr, style: CustomTextStyles.titleMediumGray50007)), SizedBox(height: 11.v), _buildLoginWithGoogle(context), SizedBox(height: 17.v), _buildLoginWithFacebook(context), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 42.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_already_have_an2".tr, style: CustomTextStyles.bodyMediumOnPrimary15), TextSpan(text: "lbl_signin2".tr, style: CustomTextStyles.bodyMediumPrimary)]), textAlign: TextAlign.left)), SizedBox(height: 5.v)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 40.v, leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.fromLTRB(24.h, 9.v, 329.h, 9.v))); } 
/// Section Widget
Widget _buildFullName(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 10.h), child: BlocSelector<SignUpBloc, SignUpState, TextEditingController?>(selector: (state) => state.fullNameController, builder: (context, fullNameController) {return CustomTextFormField(controller: fullNameController, hintText: "lbl_full_name".tr, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 17.v, 14.h, 17.v), child: CustomImageView(imagePath: ImageConstant.imgLock, height: 22.adaptSize, width: 22.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;}, contentPadding: EdgeInsets.only(top: 19.v, right: 30.h, bottom: 19.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL12, fillColor: appTheme.whiteA700);})); } 
/// Section Widget
Widget _buildMobileNumber(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 10.h), child: BlocSelector<SignUpBloc, SignUpState, TextEditingController?>(selector: (state) => state.mobileNumberController, builder: (context, mobileNumberController) {return CustomTextFormField(controller: mobileNumberController, hintText: "lbl_mobile_number".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.phone, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 17.v, 13.h, 17.v), child: CustomImageView(imagePath: ImageConstant.imgCall, height: 22.adaptSize, width: 22.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;}, contentPadding: EdgeInsets.only(top: 19.v, right: 30.h, bottom: 19.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL12, fillColor: appTheme.whiteA700);})); } 
/// Section Widget
Widget _buildLoginWithGoogle(BuildContext context) { return CustomElevatedButton(height: 56.v, text: "msg_login_with_google".tr, margin: EdgeInsets.only(left: 21.h, right: 33.h), leftIcon: Container(margin: EdgeInsets.only(right: 19.h), child: CustomImageView(imagePath: ImageConstant.imgGoogle, height: 26.adaptSize, width: 26.adaptSize)), buttonStyle: CustomButtonStyles.outlineBlueGrayF, buttonTextStyle: CustomTextStyles.bodyLargeOnPrimary, onPressed: () {onTapLoginWithGoogle(context);}); } 
/// Section Widget
Widget _buildLoginWithFacebook(BuildContext context) { return CustomElevatedButton(height: 56.v, text: "msg_login_with_facebook".tr, margin: EdgeInsets.only(left: 20.h, right: 32.h), leftIcon: Container(margin: EdgeInsets.only(right: 19.h), child: CustomImageView(imagePath: ImageConstant.imgFacebook, height: 30.adaptSize, width: 30.adaptSize)), buttonStyle: CustomButtonStyles.outlineBlueGrayF, buttonTextStyle: CustomTextStyles.bodyLargeOnPrimary, onPressed: () {onTapLoginWithFacebook(context);}); } 
/// Navigates to the verificationScreen when the action is triggered.
onTapArrowLeft(BuildContext context) { NavigatorService.pushNamed(AppRoutes.verificationScreen, ); } 
onTapLoginWithGoogle(BuildContext context) async  {         await GoogleAuthHelper().googleSignInProcess().then((googleUser) {
          if(googleUser!=null){
            //TODO Actions to be performed after signin
          } else {
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('user data is empty')));
          }
        }).catchError((onError) {
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(onError.toString())));
        });
         } 
onTapLoginWithFacebook(BuildContext context) async  {             await FacebookAuthHelper().facebookSignInProcess().then((facebookUser) {
              //TODO Actions to be performed after signin
              }).catchError((onError) {
              ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(onError.toString())));
            });
             } 
 }
