import 'bloc/onboarding_two_bloc.dart';import 'models/on_boarding_page_view_model.dart';import 'models/onboarding_two_model.dart';import 'package:flutter/material.dart';import 'package:sanjay_s_application2/core/app_export.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';
// ignore_for_file: must_be_immutable
class OnboardingTwoScreen extends StatelessWidget {OnboardingTwoScreen({Key? key}) : super(key: key);

PageController pageController = PageController();

List<OnBoardingPageViewModel> onboardingPageViewModelList = [OnBoardingPageViewModel(image: ImageConstant.imgRectangle19, buildingBetter: "msg_explore_upcoming".tr, createAUnique: "msg_in_publishing_and".tr), OnBoardingPageViewModel(image: ImageConstant.imgRectangle19401x375, buildingBetter: "msg_explore_upcoming".tr, createAUnique: "msg_in_publishing_and".tr)];

static Widget builder(BuildContext context) { return BlocProvider<OnboardingTwoBloc>(create: (context) => OnboardingTwoBloc(OnboardingTwoState(onboardingTwoModelObj: OnboardingTwoModel()))..add(OnboardingTwoInitialEvent()), child: OnboardingTwoScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<OnboardingTwoBloc, OnboardingTwoState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 685.v, child: PageView(controller: pageController, scrollDirection: Axis.horizontal, children: List.generate(onboardingPageViewModelList.length, (index) {return Column(children: [CustomImageView(imagePath: onboardingPageViewModelList[index].image!, height: 401.v, width: 375.h, radius: BorderRadius.vertical(bottom: Radius.circular(20.h))), Container(width: 256.h, margin: EdgeInsets.only(top: 45.v), child: Text(onboardingPageViewModelList[index].buildingBetter!, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.headlineSmallBlack90001Medium.copyWith(color: appTheme.black90001, height: 1.42))), Opacity(opacity: 0.8, child: Container(width: 282.h, margin: EdgeInsets.only(left: 46.h, top: 39.v, right: 45.h), child: Text(onboardingPageViewModelList[index].createAUnique!, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLargeBlack90001.copyWith(color: appTheme.black90001.withOpacity(0.64), height: 1.56))))]);}))), SizedBox(height: 5.v), GestureDetector(onTap: () {onTapDirectional(context);}, child: Padding(padding: EdgeInsets.symmetric(horizontal: 40.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.5, child: Text("lbl_skip".tr, style: CustomTextStyles.titleMediumBlack90001)), Spacer(flex: 3), SmoothPageIndicator(controller: pageController, count: 2, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 8, activeDotColor: appTheme.black90001, dotColor: appTheme.black90001.withOpacity(0.42), dotHeight: 8.v, dotWidth: 8.h), onDotClicked: (value) {pageController.jumpToPage(value);}), Spacer(flex: 2), Text("lbl_next".tr, style: CustomTextStyles.titleMediumMedium18)])))]))));}); } 
/// Common widget
Widget _buildZero(BuildContext context, {required String imageProp, required String textProp1, required String textProp2, }) { return Column(children: [CustomImageView(imagePath: imageProp, height: 401.v, width: 375.h, radius: BorderRadius.vertical(bottom: Radius.circular(20.h))), SizedBox(height: 45.v), SizedBox(width: 256.h, child: Text(textProp1, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.headlineSmallBlack90001Medium.copyWith(color: appTheme.black90001, height: 1.42))), SizedBox(height: 39.v), Opacity(opacity: 0.8, child: Container(width: 282.h, margin: EdgeInsets.only(left: 46.h, right: 45.h), child: Text(textProp2, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLargeBlack90001.copyWith(color: appTheme.black90001.withOpacity(0.64), height: 1.56))))]); } 
/// Navigates to the signInScreen when the action is triggered.
onTapDirectional(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signInScreen, ); } 
 }
