import '../invites_screen/widgets/petalsoflovetext_item_widget.dart';import '../invites_screen/widgets/savethedatecards_item_widget.dart';import '../invites_screen/widgets/text_item_widget.dart';import 'bloc/invites_bloc.dart';import 'models/invites_model.dart';import 'models/petalsoflovetext_item_model.dart';import 'models/savethedatecards_item_model.dart';import 'models/text_item_model.dart';import 'package:flutter/material.dart';import 'package:sanjay_s_application2/core/app_export.dart';import 'package:sanjay_s_application2/presentation/all_cities_photographer_page/all_cities_photographer_page.dart';import 'package:sanjay_s_application2/widgets/app_bar/appbar_subtitle.dart';import 'package:sanjay_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:sanjay_s_application2/widgets/custom_bottom_bar.dart';
// ignore_for_file: must_be_immutable
class InvitesScreen extends StatelessWidget {InvitesScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<InvitesBloc>(create: (context) => InvitesBloc(InvitesState(invitesModelObj: InvitesModel()))..add(InvitesInitialEvent()), child: InvitesScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 17.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 24.h), child: Column(children: [_buildWeddingCards(context), SizedBox(height: 21.v), _buildVideoInvites(context), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: Text("msg_save_the_date_cards".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 13.v), _buildSaveTheDateCards(context), SizedBox(height: 121.v), _buildFortyFive(context), SizedBox(height: 5.v), _buildDecoration(context)]))))])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 60.v, leadingWidth: 43.000002.h, leading: Container(height: 12.v, width: 15.000002.h, margin: EdgeInsets.only(left: 28.h, top: 21.v, bottom: 22.v), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeftOnprimary12x6, height: 12.v, width: 6.h, alignment: Alignment.centerLeft, margin: EdgeInsets.only(right: 9.h), onTap: () {onTapImgArrowLeft(context);}), CustomImageView(imagePath: ImageConstant.imgVectorOnprimary, height: 2.v, width: 15.h, alignment: Alignment.bottomCenter, margin: EdgeInsets.only(top: 6.v, bottom: 3.v))])), title: AppbarSubtitle(text: "lbl_invites".tr, margin: EdgeInsets.only(left: 13.h))); } 
/// Section Widget
Widget _buildWeddingCards(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_wedding_cards".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 11.v), SizedBox(height: 157.v, child: BlocSelector<InvitesBloc, InvitesState, InvitesModel?>(selector: (state) => state.invitesModelObj, builder: (context, invitesModelObj) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 18.h);}, itemCount: invitesModelObj?.textItemList.length ?? 0, itemBuilder: (context, index) {TextItemModel model = invitesModelObj?.textItemList[index] ?? TextItemModel(); return TextItemWidget(model);});}))]); } 
/// Section Widget
Widget _buildVideoInvites(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_video_invites".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 13.v), SizedBox(height: 157.v, child: BlocSelector<InvitesBloc, InvitesState, InvitesModel?>(selector: (state) => state.invitesModelObj, builder: (context, invitesModelObj) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 18.h);}, itemCount: invitesModelObj?.petalsoflovetextItemList.length ?? 0, itemBuilder: (context, index) {PetalsoflovetextItemModel model = invitesModelObj?.petalsoflovetextItemList[index] ?? PetalsoflovetextItemModel(); return PetalsoflovetextItemWidget(model);});}))]); } 
/// Section Widget
Widget _buildSaveTheDateCards(BuildContext context) { return SizedBox(height: 157.v, child: BlocSelector<InvitesBloc, InvitesState, InvitesModel?>(selector: (state) => state.invitesModelObj, builder: (context, invitesModelObj) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 18.h);}, itemCount: invitesModelObj?.savethedatecardsItemList.length ?? 0, itemBuilder: (context, index) {SavethedatecardsItemModel model = invitesModelObj?.savethedatecardsItemList[index] ?? SavethedatecardsItemModel(); return SavethedatecardsItemWidget(model);});})); } 
/// Section Widget
Widget _buildFortyFive(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SingleChildScrollView(scrollDirection: Axis.horizontal, padding: EdgeInsets.only(left: 362.h), child: IntrinsicWidth(child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgStarSymbolIconYellowA700, height: 13.adaptSize, width: 13.adaptSize, margin: EdgeInsets.only(bottom: 5.v)), CustomImageView(imagePath: ImageConstant.imgStarSymbolIconYellowA700, height: 13.adaptSize, width: 13.adaptSize, margin: EdgeInsets.only(left: 5.h, top: 5.v)), CustomImageView(imagePath: ImageConstant.imgStarSymbolIconYellowA700, height: 13.adaptSize, width: 13.adaptSize, margin: EdgeInsets.only(left: 6.h, top: 5.v)), CustomImageView(imagePath: ImageConstant.imgStarSymbolIconYellowA700, height: 13.adaptSize, width: 13.adaptSize, margin: EdgeInsets.only(left: 5.h, top: 5.v)), Padding(padding: EdgeInsets.only(left: 6.h, top: 5.v), child: Text("lbl_4_5".tr, style: theme.textTheme.labelMedium))])))); } 
/// Section Widget
Widget _buildDecoration(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 8.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_decoration".tr, style: CustomTextStyles.labelLarge12), Spacer(flex: 54), Text("lbl_photographer".tr, style: CustomTextStyles.labelLarge12), Spacer(flex: 45), Text("lbl_de".tr, style: CustomTextStyles.labelLarge12)])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Homepage: return AppRoutes.allCitiesPhotographerPage; case BottomBarEnum.Vendor: return "/"; case BottomBarEnum.Einvites: return "/"; case BottomBarEnum.Wishlist: return "/"; case BottomBarEnum.Checklist: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.allCitiesPhotographerPage: return AllCitiesPhotographerPage(); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapImgArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
