import 'bloc/add_my_checklist_bloc.dart';import 'models/add_my_checklist_model.dart';import 'package:flutter/material.dart';import 'package:sanjay_s_application2/core/app_export.dart';import 'package:sanjay_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:sanjay_s_application2/widgets/app_bar/appbar_subtitle.dart';import 'package:sanjay_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:sanjay_s_application2/widgets/custom_icon_button.dart';import 'package:sanjay_s_application2/widgets/custom_text_form_field.dart';class AddMyChecklistScreen extends StatelessWidget {const AddMyChecklistScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AddMyChecklistBloc>(create: (context) => AddMyChecklistBloc(AddMyChecklistState(addMyChecklistModelObj: AddMyChecklistModel()))..add(AddMyChecklistInitialEvent()), child: AddMyChecklistScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 11.v), child: Column(children: [SizedBox(height: 10.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_task_1".tr, style: theme.textTheme.bodyMedium))), SizedBox(height: 17.v), _buildEnterHereRow(context), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_tasks_2".tr, style: theme.textTheme.bodyMedium))), SizedBox(height: 12.v), _buildTaskTwoRow(context), SizedBox(height: 21.v), _buildTaskTwoColumn(context), SizedBox(height: 21.v), _buildTaskTwoColumn1(context), SizedBox(height: 21.v), _buildTasksCounterColumn(context), SizedBox(height: 21.v), _buildTaskTwoColumn2(context), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_tasks_7".tr, style: theme.textTheme.bodyMedium)))])), bottomNavigationBar: _buildTaskTwoColumn3(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 47.v, leadingWidth: 46.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 15.v)), title: AppbarSubtitle(text: "msg_add_my_checklist".tr, margin: EdgeInsets.only(left: 11.h))); } 
/// Section Widget
Widget _buildEnterHereRow(BuildContext context) { return Row(crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 35.v), child: Divider())), Expanded(child: Padding(padding: EdgeInsets.only(bottom: 13.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 8.v), child: Text("msg_enter_here".tr, style: CustomTextStyles.bodySmallGray40002)), CustomImageView(imagePath: ImageConstant.imgGroup18858, height: 23.adaptSize, width: 23.adaptSize)])))]); } 
/// Section Widget
Widget _buildTaskTwoRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 35.v), child: Divider())), Padding(padding: EdgeInsets.only(bottom: 22.v), child: BlocSelector<AddMyChecklistBloc, AddMyChecklistState, TextEditingController?>(selector: (state) => state.taskTwoController, builder: (context, taskTwoController) {return CustomTextFormField(width: 76.h, controller: taskTwoController, hintText: "msg_enter_here".tr, hintStyle: CustomTextStyles.bodySmallGray40002);})), Spacer(), CustomImageView(imagePath: ImageConstant.imgGroup18858, height: 23.adaptSize, width: 23.adaptSize, margin: EdgeInsets.only(top: 2.v, right: 9.h, bottom: 11.v))])); } 
/// Section Widget
Widget _buildTaskTwoColumn(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_tasks_3".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 16.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 36.v), child: Divider())), Expanded(child: Padding(padding: EdgeInsets.only(top: 1.v, bottom: 22.v), child: BlocSelector<AddMyChecklistBloc, AddMyChecklistState, TextEditingController?>(selector: (state) => state.taskTwoController1, builder: (context, taskTwoController1) {return CustomTextFormField(controller: taskTwoController1, hintText: "msg_enter_here".tr, hintStyle: CustomTextStyles.bodySmallGray40002);}))), CustomImageView(imagePath: ImageConstant.imgGroup18858, height: 23.adaptSize, width: 23.adaptSize, margin: EdgeInsets.only(left: 12.h, bottom: 14.v))])])); } 
/// Section Widget
Widget _buildTaskTwoColumn1(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_tasks_4".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(right: 1.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 35.v), child: Divider())), Padding(padding: EdgeInsets.only(bottom: 22.v), child: BlocSelector<AddMyChecklistBloc, AddMyChecklistState, TextEditingController?>(selector: (state) => state.taskTwoController2, builder: (context, taskTwoController2) {return CustomTextFormField(width: 76.h, controller: taskTwoController2, hintText: "msg_enter_here".tr, hintStyle: CustomTextStyles.bodySmallGray40002);})), Spacer(), CustomImageView(imagePath: ImageConstant.imgGroup18858, height: 23.adaptSize, width: 23.adaptSize, margin: EdgeInsets.only(right: 9.h, bottom: 12.v))]))])); } 
/// Section Widget
Widget _buildTasksCounterColumn(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_tasks_5".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 12.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 1.v, width: 340.h, margin: EdgeInsets.only(top: 35.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 340.h, child: Divider())), Align(alignment: Alignment.center, child: SizedBox(width: 340.h, child: Divider()))])), Container(height: 14.v, width: 76.h, margin: EdgeInsets.only(bottom: 22.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("msg_enter_here".tr, style: CustomTextStyles.bodySmallGray40002)), Align(alignment: Alignment.center, child: Text("msg_enter_here".tr, style: CustomTextStyles.bodySmallGray40002))])), Spacer(), Padding(padding: EdgeInsets.only(top: 11.v, bottom: 10.v), child: Text("lbl_12_10_2001".tr, style: CustomTextStyles.labelLargeGray60001))])])); } 
/// Section Widget
Widget _buildTaskTwoColumn2(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_tasks_6".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 17.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 35.v), child: Divider())), Expanded(child: Padding(padding: EdgeInsets.only(bottom: 22.v), child: BlocSelector<AddMyChecklistBloc, AddMyChecklistState, TextEditingController?>(selector: (state) => state.taskTwoController3, builder: (context, taskTwoController3) {return CustomTextFormField(controller: taskTwoController3, hintText: "msg_enter_here".tr, hintStyle: CustomTextStyles.bodySmallGray40002);}))), CustomImageView(imagePath: ImageConstant.imgGroup18858, height: 23.adaptSize, width: 23.adaptSize, margin: EdgeInsets.only(left: 12.h, bottom: 12.v))])])); } 
/// Section Widget
Widget _buildTaskTwoColumn3(BuildContext context) { return Container(height: 87.v, width: 340.h, margin: EdgeInsets.only(left: 17.h, right: 17.h, bottom: 22.v), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(left: 4.h, right: 9.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Padding(padding: EdgeInsets.only(bottom: 8.v), child: BlocSelector<AddMyChecklistBloc, AddMyChecklistState, TextEditingController?>(selector: (state) => state.taskTwoController4, builder: (context, taskTwoController4) {return CustomTextFormField(controller: taskTwoController4, hintText: "msg_enter_here".tr, hintStyle: CustomTextStyles.bodySmallGray40002, textInputAction: TextInputAction.done);}))), CustomImageView(imagePath: ImageConstant.imgGroup18858, height: 23.adaptSize, width: 23.adaptSize, margin: EdgeInsets.only(left: 12.h))])), Padding(padding: EdgeInsets.only(top: 13.v), child: Divider())])), Align(alignment: Alignment.bottomCenter, child: SizedBox(height: 58.v, width: 271.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapArrowLeft(context);}, child: Container(height: 58.v, width: 271.h, padding: EdgeInsets.all(14.h), decoration: AppDecoration.outlineIndigoF.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: CustomIconButton(height: 30.adaptSize, width: 30.adaptSize, padding: EdgeInsets.all(8.h), decoration: IconButtonStyleHelper.fillIndigoA, alignment: Alignment.centerRight, child: CustomImageView(imagePath: ImageConstant.imgArrowLeft))))), Align(alignment: Alignment.center, child: Text("lbl_add".tr.toUpperCase(), style: CustomTextStyles.titleMediumWhiteA700))])))])); } 
/// Navigates to the myChecklistScreen when the action is triggered.
onTapArrowLeft(BuildContext context) { NavigatorService.pushNamed(AppRoutes.myChecklistScreen, ); } 
 }
