import 'bloc/you_want_to_choose_bloc.dart';import 'models/you_want_to_choose_model.dart';import 'package:flutter/material.dart';import 'package:sanjay_s_application2/core/app_export.dart';import 'package:sanjay_s_application2/widgets/custom_elevated_button.dart';import 'package:sanjay_s_application2/presentation/choosed_bottomsheet/choosed_bottomsheet.dart';class YouWantToChooseDialog extends StatelessWidget {const YouWantToChooseDialog({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<YouWantToChooseBloc>(create: (context) => YouWantToChooseBloc(YouWantToChooseState(youWantToChooseModelObj: YouWantToChooseModel()))..add(YouWantToChooseInitialEvent()), child: YouWantToChooseDialog()); } 
@override Widget build(BuildContext context) { return Container(width: 318.h, padding: EdgeInsets.symmetric(horizontal: 28.h, vertical: 39.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 8.v), Container(height: 127.adaptSize, width: 127.adaptSize, padding: EdgeInsets.all(37.h), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder63), child: CustomImageView(imagePath: ImageConstant.imgPaperPlane1, height: 52.adaptSize, width: 52.adaptSize, alignment: Alignment.center)), SizedBox(height: 43.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 30.h), child: Text("msg_you_want_to_choose".tr, style: theme.textTheme.titleLarge))), SizedBox(height: 17.v), SizedBox(width: 259.h, child: Text("msg_are_you_sure_you2".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodySmallBlack90001)), SizedBox(height: 36.v), CustomElevatedButton(height: 52.v, text: "lbl_yes".tr, margin: EdgeInsets.only(left: 5.h, right: 4.h), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700_1, onPressed: () {onTapYes(context);}), SizedBox(height: 10.v), CustomElevatedButton(height: 52.v, text: "lbl_no".tr, margin: EdgeInsets.only(left: 5.h, right: 4.h), buttonStyle: CustomButtonStyles.fillOnError, buttonTextStyle: theme.textTheme.bodyLarge!)])); } 

/// Displays a bottom sheet widget using the [showModalBottomSheet] method 
/// of the [Scaffold] class with [isScrollControlled] set to true.
///
/// The bottom sheet is built using the [ChoosedBottomsheet]
/// class and the [builder] method of the bottom sheet is passed the
/// [BuildContext] object.
onTapYes(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>ChoosedBottomsheet.builder(context),isScrollControlled: true); } 
 }
