import 'bloc/edit_profile_bloc.dart';import 'models/edit_profile_model.dart';import 'package:flutter/material.dart';import 'package:sanjay_s_application2/core/app_export.dart';import 'package:sanjay_s_application2/core/utils/validation_functions.dart';import 'package:sanjay_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:sanjay_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:sanjay_s_application2/widgets/custom_elevated_button.dart';import 'package:sanjay_s_application2/widgets/custom_floating_text_field.dart';
// ignore_for_file: must_be_immutable
class EditProfileScreen extends StatelessWidget {EditProfileScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<EditProfileBloc>(create: (context) => EditProfileBloc(EditProfileState(editProfileModelObj: EditProfileModel()))..add(EditProfileInitialEvent()), child: EditProfileScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<EditProfileBloc, EditProfileState>(builder: (context, state) {return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 17.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRectangle4158, height: 91.adaptSize, width: 91.adaptSize, radius: BorderRadius.circular(45.h), alignment: Alignment.center), SizedBox(height: 13.v), Align(alignment: Alignment.center, child: Text("lbl_upload_photo".tr, style: CustomTextStyles.titleMediumPrimary)), SizedBox(height: 44.v), Padding(padding: EdgeInsets.only(left: 9.h), child: Text("lbl_name".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 9.h), child: Text("lbl_ashfak_sayem".tr, style: CustomTextStyles.titleMediumMedium_1)), SizedBox(height: 18.v), Divider(indent: 5.h), SizedBox(height: 21.v), Padding(padding: EdgeInsets.only(left: 5.h), child: BlocSelector<EditProfileBloc, EditProfileState, TextEditingController?>(selector: (state) => state.mobilevalueController, builder: (context, mobilevalueController) {return CustomFloatingTextField(controller: mobilevalueController, labelText: "lbl_mobile".tr, labelStyle: CustomTextStyles.titleMediumMedium_1, hintText: "lbl_mobile".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.phone, validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;});})), SizedBox(height: 23.v), Padding(padding: EdgeInsets.only(left: 9.h), child: Text("msg_email_optional".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 9.h), child: Text("lbl_abcd_email_com".tr, style: CustomTextStyles.titleMediumMedium_1)), SizedBox(height: 18.v), Divider(indent: 5.h), SizedBox(height: 23.v), Padding(padding: EdgeInsets.only(left: 9.h), child: Text("msg_gender_optional".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 11.v), _buildMaleRow(context), SizedBox(height: 19.v), Divider(indent: 5.h), SizedBox(height: 72.v), CustomElevatedButton(text: "lbl_save".tr.toUpperCase(), margin: EdgeInsets.symmetric(horizontal: 37.h), onPressed: () {onTapSAVE(context);}, alignment: Alignment.center), SizedBox(height: 5.v)])))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 32.v, leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 24.h, right: 329.h))); } 
/// Section Widget
Widget _buildMaleRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 9.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_male".tr, style: CustomTextStyles.titleMediumMedium_1), CustomImageView(imagePath: ImageConstant.imgMenu12012x12, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(top: 4.v, bottom: 2.v))])); } 
/// Navigates to the profileSavedOneScreen when the action is triggered.
onTapSAVE(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileSavedOneScreen, ); } 
 }
